travis:
  secure:
    BINSTAR_TOKEN: g+2CFWoaonA+E6BCrDhZaCa6wFBBemmpa0oZ6HoOuadsjwLUpXeO11P3kgHWmtxkgt/Hiwqfh7GujuqM/A+/cYoqXnt3pGNQpM+YPVrKlUisJaHjFY25/HUM6R2YdjjogkPJNRkzIjLJyCEnc6Ih5pAMCNI9H+ljh4fCJvfXvVZWCasenhyFK3zaOexpodC0xAaLzNU60oLL6BCeNG5RnUMkMA1YsvdpKg+yPD9sDyhN7hPtIsr0McObQJoYQEZqbhkcXFK2zL1vfgGyzqfJ6Xghc0X1SymDVBJQVt9JKRJFXAh9qq7VOVvvBNuLaP9g7zAT3hWwOxCJ9TSIImU33zQlH2K/kRmlFoAQCuzK8Be8whx1BR+5LJwstufxEmg29o9naZ2y4sS/aSwNAzFMhvHDo0j697iWwqzVMYfY7LNXiw50uAa7wI6alJMvQIH0Kbjt0rFtWCrXSA+Ha8XjqxdUv0ZE4OoYPJZwphF3Z7Pj33/F2EsGrcMiamCKF3kCHi3DBsEju6eJE8adLu4aXkzT9+IJ+Ni2I1yQDZzn4vb1DlZYxppgUlIEynkEKarMyKXE0c8MFhHz/kTdKXz4kz0sOXIrorBRlwXwM3ISWyDl6ZrkFzy+YMf6VO273gzTx77BXHiCYsZPJRWGFuSDoJWyVfJ7YXEAwEen448uwuI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
